settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: lllxy
    name: www.lllxy.net
    url: 'https://www.lllxy.net/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: nextcloud
    name: cloud.lllxy.net
    url: 'https://cloud.lllxy.net/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
    
  - id: conchbrain
    name: conchbrain
    url: 'https://www.conchbrain.club/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: cloudshell
    name: cloudshell
    url: 'https://cloudshell.conchbrain.club/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: music
    name: music.conchbrain.club
    url: 'https://music.conchbrain.club/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
  
  - id: kvstorage
    name: storage.conchbrain.club
    url: 'https://storage.conchbrain.club/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: cors
    name: cors.conchbrain.club
    url: 'https://cors.conchbrain.club/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: proxy
    name: proxy.conchbrain.club
    url: 'https://proxy.conchbrain.club/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: mixstore
    name: mixstore
    url: 'https://mixstore.conchbrain.club/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: mixapi
    name: mixapi
    url: 'https://mixapi.conchbrain.club/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
    
  - id: proxy2
    name: mixproxy
    url: 'https://proxy2.conchbrain.club/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

